### ISSUE TITLE
Dashboard roadmap document

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#118]
## Type of Issue
Create a document outlining the roadmap 

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [x] Documentation Ask

**Comment by kavyasrinet** [comment]
This is now done [here](https://docs.google.com/document/d/1GbXDGagwuc87eadgdEdprGJre4WE9yPFnBup-B65j8U/edit )
