### ISSUE TITLE
UX requests for AutoComplete tool

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#318]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

**Comment by Rebecca-Qian** [comment]
> Once I reach the end of annotations, it says "congrats" but still keeps showing the last text I annotated with empty dict which confuses me whether I should that empty dict for the same command ? Is it possible to just wipe out the text box + action dict (not even show {} , just empty it) when we reach end of annotations ?

like everything is empty?

**Comment by Rebecca-Qian** [comment]
> proper re-focusing/re-centering cursor after [enter] jsonification
@aszlam do you mean you can't use "enter" to go to the next line? What do you think about using a different key eg. tab to do the autocomplete/JSON conversions?
