### ISSUE TITLE
[Dashboard] Location tracking in Voxel world is unreliable

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#332]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Often move commands fail due to errors in location tracking, eg. the speaker position is not updated when they move so "come here" causes the agent to go to the starting position. This also causes other failures like:
- "follow me"
- "build X behind me" -> builds behind speaker's starting position

Another set of errors but not sure if related, is "go to X" sometimes is inaccurate.

## Current Behavior

Speaker's location is not resolved dynamically, plus other location inaccuracies.

## Expected Behavior

Speaker's location updated in real time

## Steps to reproduce

Go to `craftassist.io` and spin up a new container.
Move the speaker around, and ask agent to come to speaker

**Comment by snyxan** [comment]
This is expected. Not a bug report but a feature request.
