### ISSUE TITLE
Memory refactor tracker

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#417]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Checklist

The branch is: `kavya/modular_memory_refactor` and is based off this issue: https://github.com/facebookresearch/droidlet/issues/337

Following is the checklist:

- [x] sql_memory.py, remove:
  - [x] from droidlet.interpreter.task import Task
- [x] memory_values.py:
  - [x] from droidlet.base_util import TICKS_PER_SEC, TICKS_PER_MINUTE, TICKS_PER_HOUR
- [x] memory_nodes.py:
  - [x] from droidlet.base_util import XYZ, POINT_AT_TARGET, to_player_struct
- [x] craftassist/sql_script delete
- [x] craftassist/base_sql_mock_environment.py delete
- [x] craftassist/mc_memory:
  - [x] from ...lowlevel.minecraft import specs as minecraft_specs
  - [x] from ...interpreter.craftassist import dance
  - [x] from droidlet.lowlevel.minecraft.build_utils import npy_to_blocks_list
  - [x] from droidlet.base_util import XYZ, Block
  - [x] from droidlet.interpreter.craftassist.word_maps import SPAWN_OBJECTS
- [x] documents/ -> droidlet/documents
  - [x] fix all references
- [x] loco_memory_nodes:
  - [x] from droidlet.base_util import XYZ, Pos
- [x] loco_memory:
  - [x] from droidlet.interpreter.robot.dance import add_default_dances
- [ ] Fix all os.path.joins
- [x] Fix minecraft_specs imports in (remove `as minecraft_specs`):
  - [x] mc_memory.py
  - [x] mc_memory_nodes.py
  - [x] heuristic_perception.py
  - [x] block_helpers.py
- [x] create shared_data_struct folder and move : base_util, shared_data_structs and minecraft_specs 
- [x] cleanup base_utils
- [x] remove shared_data_struct folder
- [x] remove classes from base_utils
- [x] remove imports from other modules in base_utils
- [x] Move out craftassist_specs.py from shared folder into lowlevel
- [x] Move SPAWN_OBJECTS into lowlevel minecraft 
- [x] Add unit tests for functions in base_util.
- [x] memory_test update
- [x] Shared exception classes in shared_data_structs.py - clean 
- [x] Clean up tests in memory folder -> some dependencies still exist there
- [x] write unit tests for every function in sql_memory.py
- [x] unit tests for every function in mc_memory.py
- [x] unit tests for every function in loco_memory.py
- [x] unit tests for base_utils
- [ ] https://github.com/facebookresearch/droidlet/issues/431 : this unit test doesn't yet work

**Comment by kavyasrinet** [comment]
This is now done
