### ISSUE TITLE
Lowlevel refactor tracker

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#423]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Checklist

Parent issue: #337 

- [ ] minecraft :
  - [x] cuberite_process.py:
    - [x] from droidlet.perception import build_shape_scene
  - [x] place_blocks.py -> new folder cuberite
  - [x] repo.py -> delete and fix paths
  - [x] size_words.py moved to interpreter
  - [x] block_data -> craftassit_cuberite
  - [x] build_utils - delete and moved functions to base_util
  - [x] mc_util cleanup
  - [x] wait_for_cuberite.py move functions 
  - [x] move all relevant functions to craftassist_cuberite_utils
  - [x] minecraft_specs/read_images.py:
    - [x] remove value for home_dir 
    - [x] cleanup + refactor
  - [x] client/generate_recipes.py delete ?
- [x] locobot :
  - [x] locobot_mover.py:
    - [x] from droidlet.perception.robot import RGBDepth
    - [x] from droidlet.interpreter.robot.objects import Marker, Pos
  - [x] locobot_mover_utils.py:=
    - [x] fix : from droidlet.lowlevel.locobot.rotation import yaw_pitch to from .rotation import yaw_pitch
  - [x] locobot_util:
    - [x] duplicate : group_by function (same in base_util)
    - [x] duplicate hash_user function (same in base_util)
    - [x] shasum_file duplicate check
    - [x] class TimingWarn might be a duplicate with base_util
    - [x] euclid_dist
    - [x] manhat_dist
    - [x] XYZ, POINT_AT_TARGET, IDM , Block, Hole , T = TypeVar("T") 
  - [x] tests:
    - [x] import in test_mover: from droidlet.lowlevel.locobot.locobot_mover import LoCoBotMover
    - [x] from droidlet.lowlevel.locobot.locobot_mover_utils import in test_utils
  - [ ] remote_locobot.py:
    - [x] add use_dslam to docstring (go_to_relative, go_to_absolute
    - [ ] code for transform_pose is duplicated in depth_utils
    - [x] in_global missing in docstring for get_current_pcd
  - [x] fix import open3d as o3d in RGBDepth
 - [x] refactor base_util:
 - [ ] add tests for lowlevel
 - [x] move shapes and shape_helpers to lowlevel from perception (cuberite was using this so agent cannot send from perception)
 - [x]  remove imports from other modules in base_utils
   - [x] from droidlet.perception.craftassist.shape_helpers import SHAPE_NAMES, SHAPE_HELPERS, bid, SHAPE_FNS, shape_to_dicts
 - [ ] check droidlet.lowlevel.minecraft.mc_util for duplicate functions

**Comment by kavyasrinet** [comment]
This is now done
