### ISSUE TITLE
Tracker for additional unit tests

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#471]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Checklist

Starting this tracker for list of functions to add unit tests for. If you see any failures after the refactor, please add to this list (and the PR fixing the issue should add the test):
- [x] `build_random_shape` in craftassist's `default_behavior`
- [ ] test handle_dig (PR: https://github.com/facebookresearch/droidlet/pull/540)
- [ ] Interpreter:
   - [x] attribute_helper (PR: https://github.com/facebookresearch/droidlet/pull/510) 
      - [x] interpret_span_value
      - [x] maybe_specific_mem
      - [x] interpret_linear_extent
      - [x] interpret_task_info
    - [ ] comparator_helper.py
      - [ ] interpret_comparator
    - [ ] filter_helper.py 
    - [ ] get_memory_handler
    - [ ] interpreter_utils
    - [ ] location_helpers
    - [ ] reference_object_helpers
  - [ ] craftassist folder:
    - [ ]  block_helpers
    - [ ] dance.py
    - [x] default_behaviors
    - [ ] facing_helper
    - [ ] point_target
    - [ ] schematic_helper
    - [ ] size_words
    - [ ] spatial_reasoning
    - [ ] modify_helpers
  - [ ] locobot
    - [ ] dance
    - [ ] default_behaviors
    - [ ] facing_helper
    - [ ] point_target
    - [ ] get_memory_handler
    - [ ] spatial_reasoning
    - [ ]

**Comment by Rebecca-Qian** [comment]
Semantic parser model training script was broken during refactor. In the previous setting, the training script was in the same directory as ML modules. In the refactor the imports were converted from file imports to module imports, and since the train script was invoked from `__main__`, this broke the training script imports.

It is strictly better to keep train/inference scripts and module classes separate, so I moved the scripts out into `tools/nsp_scripts/`. Now NSP is a standalone module.

Fix is in #485

Re: unit tests, I'm working on some basic integration tests. 🙂

**Comment by snyxan** [comment]
Craftassist `perceive()` fn is failing due to parser/perception refactor. See this issue #497 and this PR #498 

We should add unittest for this part, tracked in this issue #499

**Comment by kavyasrinet** [comment]
Current code cov: https://codecov.io/gh/facebookresearch/droidlet/tree/e7e7eb4088dda3b90cba5ac99c2d02665e44ab08/droidlet

Dig into the folders

**Comment by soumith** [comment]
the coverage diffs don't look correct according to how they're supposed to look as documented in https://docs.codecov.com/docs/viewing-source-code
I'm taking a look as to why

**Comment by soumith** [comment]
ok that was the `diff` view. If we just browse the `main` branch, things look correct: https://codecov.io/gh/facebookresearch/droidlet/src/main/droidlet/dialog/dialogue_manager.py
