### ISSUE TITLE
Interpreter cleanup

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#511]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Checklist

Use this checklist if you are using this issue as a tracker:

- [x] remove lowlevel imports - block_helpers
- [x] remove dead code:
  - [x] file adtt
- [ ] clean up imports:
  - [x] remove lowlevel imports
    - [x] craftassist/block_helpers
    - [x] dance
    - [x] schematic_helper
    - [x] default_behaviors
    - [x] inventory
    - [x] spatial_reasoning
    - [x] tasks
    - [x] robot/tasks
  - [x] remove perception
    - [x] dance
    - [x] tasks
    - [x] mc_interpreter
    - [x] modify_helpers (this will be fixed in #518 )
    - [x] spatial_reasoning (this will be fixed in #518 )
  - [x] remove dialog imports: (this will be fixed in #519)
    - [ ] get_memory_handler
    - [ ] put_memory_handler
    - [ ] robot/put_memory_handler
    - [ ] mc_interpreter
    - [ ] dummy_interpreter
    - [ ] interpreter
    - [ ] reference_object_helpers
    - [ ] default_behaviors

**Comment by kavyasrinet** [comment]
Leaving out `craftassist/tasks` and `robot/tasks`
